import { HorizontalBox } from "std-widgets.slint";
import { Palette } from "common.slint";

export struct AlbumDetailsModel {

}

export component AlbumDetails inherits VerticalLayout {
    alignment: start;
    HorizontalLayout {
        spacing: 10px;
        alignment: start;
        Image {
            width: 275px;
            height: 275px;
            source: @image-url("../images/light.png");
        }
        VerticalLayout {
            alignment: start;
            spacing: 2px;
            Text {
                font-size: Palette.font-size-large;
                font-weight: Palette.font-weight-title;
                color: Palette.text-color-title;
                text: "Album Name";
            }
            Text {
                font-size: Palette.font-size-large;
                font-weight: Palette.font-weight-sub-title;
                color: Palette.text-color-sub-title;
                text: "Artist Name";
            }
            Text {
                text: "in Atmospheric Black Metal, Black Metal, Drone, Hard Rock & Metal, Metal, Rock";
            }
        }
    }
}