import { Button, VerticalBox , ScrollView, TextEdit, LineEdit} from "std-widgets.slint";
import { CardGrid } from "card_grid.slint";
import { Card, CardModel } from "card.slint";
import { PlayerBar } from "player_bar.slint";
import { NavBar } from "nav_bar.slint";

import "../fonts/Manrope/fonts/ttf/Manrope-ExtraLight.ttf";
import "../fonts/Manrope/fonts/ttf/Manrope-Light.ttf";
import "../fonts/Manrope/fonts/ttf/Manrope-Regular.ttf";
import "../fonts/Manrope/fonts/ttf/Manrope-Medium.ttf";
import "../fonts/Manrope/fonts/ttf/Manrope-SemiBold.ttf";
import "../fonts/Manrope/fonts/ttf/Manrope-Bold.ttf";
import "../fonts/Manrope/fonts/ttf/Manrope-ExtraBold.ttf";
import { ArtistDetails } from "artist_details.slint";

export component AppWindow inherits Window {
    callback navigate(string);

    in-out property <int> page: 0;

    preferred-width: 1440px;
    preferred-height: 1024px;
    default-font-size: 15px;
    default-font-weight: 400;
    default-font-family: "Manrope";
    title: "Dimple";

    // background: @linear-gradient(0deg, #43addb 0%, #edd0a0 50%, #b15bb3 100%);    
    background: @linear-gradient(0deg, #b9efff 0%, #ffffff 50%, #ffaee8 100%);    
    // background: @linear-gradient(0deg, #ff9cea 0%, #ffc7b3 50%, #ff96e8 100%);    
    
    VerticalLayout {
        padding: 20px;
        spacing: 20px;

        nav_bar := NavBar {  
            navigate(url) => { root.navigate(url); }
        }
        if page == 0: card_grid := CardGrid {
            navigate(url) => { root.navigate(url); }
        }   
        if page == 1: artist_details := ArtistDetails {  
        }
        Rectangle {
            vertical-stretch: 1;
        }
        player_bar := PlayerBar { 

        }
    }
}
