import { Button, VerticalBox , ScrollView, TextEdit, LineEdit, GroupBox} from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "card_grid.slint";
import { Card, CardAdapter } from "card.slint";
import { PlayerBar } from "player_bar.slint";
import { ArtistDetails, ArtistDetailsAdapter } from "artist_details.slint";
import { ReleaseGroupDetails, ReleaseGroupDetailsAdapter } from "release_group_details.slint";
import { Palette, Navigator, LinkAdapter, ImageLinkAdapter , Tag} from "common.slint";
import { StyleMetrics , HorizontalBox} from "std-widgets.slint";
import { ReleaseGroupDetails } from "release_group_details.slint";
import { ReleaseDetails, ReleaseDetailsModel } from "release_details.slint";
import { RecordingDetails, RecordingDetailsAdapter } from "recording_details.slint";
import { SideBar } from "side_bar.slint";
import { Home } from "home.slint";
import { Settings, SettingsAdapter } from "settings.slint";

export { Navigator, LinkAdapter, ImageLinkAdapter, CardAdapter, Palette }

// import "../fonts/Manrope/fonts/ttf/Manrope-Bold.ttf";
// import "../fonts/Manrope/fonts/ttf/Manrope-ExtraBold.ttf";
// import "../fonts/Manrope/fonts/ttf/Manrope-ExtraLight.ttf";
// import "../fonts/Manrope/fonts/ttf/Manrope-Light.ttf";
// import "../fonts/Manrope/fonts/ttf/Manrope-Medium.ttf";
// import "../fonts/Manrope/fonts/ttf/Manrope-Regular.ttf";
// import "../fonts/Manrope/fonts/ttf/Manrope-SemiBold.ttf";

import "../fonts/Roboto/Roboto-Black.ttf";
import "../fonts/Roboto/Roboto-BlackItalic.ttf";
import "../fonts/Roboto/Roboto-Bold.ttf";
import "../fonts/Roboto/Roboto-BoldItalic.ttf";
import "../fonts/Roboto/Roboto-Italic.ttf";
import "../fonts/Roboto/Roboto-Light.ttf";
import "../fonts/Roboto/Roboto-LightItalic.ttf";
import "../fonts/Roboto/Roboto-Medium.ttf";
import "../fonts/Roboto/Roboto-MediumItalic.ttf";
import "../fonts/Roboto/Roboto-Regular.ttf";
import "../fonts/Roboto/Roboto-Thin.ttf";
import "../fonts/Roboto/Roboto-ThinItalic.ttf";

export component AppWindow inherits Window {
    in-out property <int> page: 1;
    // TODO Note to self: Currently you can't expose properties on
    // sub-components, so all this is needed.
    in-out property <CardGridAdapter> card-grid-adapter;
    in-out property <ArtistDetailsAdapter> artist-details;
    in-out property <ReleaseGroupDetailsAdapter> release-group-details;
    in-out property <ReleaseDetailsModel> release-details;
    in-out property <RecordingDetailsAdapter> recording-details;
    in-out property <SettingsAdapter> settings-adapter;
    
    title: "Dimple";
    icon: @image-url("../images/icon_512x512.png");
    preferred-width: 1440px;
    preferred-height: 1024px;

    VerticalLayout {
        padding: 8px;
        padding-top: 4px;
        spacing: 4px;
        HorizontalLayout {
            spacing: 8px;
            padding: 0;
            GroupBox {
                SideBar {
                }
            }
            GroupBox {
                horizontal-stretch: 1;
                Rectangle {
                    if page == 0: VerticalLayout {
                        // TODO playing around with tags
                        // HorizontalBox {
                        //     padding-top: 0;
                        //     padding-left: 0;
                        //     alignment: start;
                        //     Tag {
                        //         color: #bd6b3f;
                        //         name: "Artists";
                        //         font-color: StyleMetrics.default-text-color;
                        //         font-weight: 700;
                        //     }
                        //     Tag {
                        //         color: #3c9c8a;
                        //         name: "Albums";
                        //         font-color: StyleMetrics.default-text-color;
                        //         font-weight: 700;
                        //     }
                        //     Tag {
                        //         color: #4e4cd9;
                        //         name: "Genres";
                        //         font-color: StyleMetrics.default-text-color;
                        //         font-weight: 700;
                        //     }
                        //     Tag {
                        //         color: #963fc5;
                        //         name: "Playlists";
                        //         font-color: StyleMetrics.default-text-color;
                        //         font-weight: 700;
                        //     }
                        // }
                        ScrollView {                        
                            card-grid := CardGrid {
                                cards: root.card-grid-adapter.cards;
                                parent-width: parent.width;
                            }
                        }
                        Text {
                            horizontal-alignment: right;
                            text: card-grid-adapter.cards.length + " items";
                        }
                    }
                    if page == 1: ArtistDetails {  
                        model: root.artist-details;
                    }
                    if page == 2: ReleaseGroupDetails {  
                        model: root.release-group-details;
                    }
                    if page == 3: ReleaseDetails {  
                        model: root.release-details;
                    }                
                    if page == 4: RecordingDetails {  
                        model: root.recording-details;
                    }
                    if page == 5: Home {  
                        // model: root.recording-details;
                    }
                    if page == 6: Settings {  
                        adapter: root.settings-adapter;
                    }
                }
            }    
        }   
        GroupBox {
            vertical-stretch: 0;
            PlayerBar {
            }
        }
    }
}
