import { Button, VerticalBox , ScrollView} from "std-widgets.slint";

export component Card inherits VerticalLayout {
    spacing: 2px;
    Rectangle {
        border-radius: 6px;
        clip: true;
        Image {
            source: @image-url("../images/light.png");
            min-width: 250px;
            min-height: 250px;
        }    
    }
    Rectangle {
        width: 1px;
        height: 2px;
    }
    Text {
        font-weight: 900;
        text: "Focus Infinite Ring";
    }
    Text {
        color: #5d5d5d;
        text: "Jellyfish Brothers";
    }
}

// TODO the way Music does it's card image sizing is very smoove. It maintains
// a constant margin on the left and right and then keeps the images between
// about 170 and 235
export component CardGrid inherits ScrollView {
    in-out property <int> n: 1000;
    in-out property <int> cols: Math.floor(self.width / 1px / 270);

    VerticalLayout {
        spacing: 20px;
        alignment: center;
        for row in Math.ceil(n / cols): HorizontalLayout {
            spacing: 20px;
            for col in cols: Card {
    
            }
        }
    }
}

export component AppWindow inherits Window {
    preferred-width: 1440px;
    preferred-height: 1024px;
    default-font-size: 14px;

    VerticalLayout {
        padding: 20px;

        HorizontalLayout {
            Button {
                text: "Home";
            }
            TextInput {
                text: "Search";
            }
        }
        CardGrid {
        }
        HorizontalLayout {
            spacing: 10px;
            Image {
                source: @image-url("../images/dark.png");
                width: 100px;
            }    
            VerticalLayout {
                Text {
                    text: "Title";
                }
                Text {
                    text: "Artist";
                }
            }
        }
    }
}
