import { Button, VerticalBox , ScrollView, TextEdit, LineEdit} from "std-widgets.slint";
import { CardGrid } from "cardgrid.slint";
import { Card } from "card.slint";

export component AppWindow inherits Window {
    preferred-width: 1440px;
    preferred-height: 1024px;
    default-font-size: 14px;

    VerticalLayout {
        padding: 20px;
        spacing: 10px;

        HorizontalLayout {
            spacing: 10px;
            Button {
                text: "Home";
            }
            Button {
                text: "Albums";
            }
            Button {
                text: "Artists";
            }
            Button {
                text: "Genres";
            }
            LineEdit {
                horizontal-stretch: 1;
                placeholder-text: "What sounds good?";
            }
        }
        CardGrid {
        }
        HorizontalLayout {
            spacing: 10px;
            Image {
                source: @image-url("../images/dark.png");
                width: 100px;
            }    
            VerticalLayout {
                Text {
                    text: "Title";
                }
                Text {
                    text: "Artist";
                }
            }
        }
    }
}
