import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { Palette } from "common.slint";

export struct ArtistDetailsModel {

}

export component ArtistDetails inherits VerticalBox {
    alignment: start;
    HorizontalBox {
        alignment: start;
        Rectangle {
            width: Palette.thumbnail-width-extra-large;
            height: Palette.thumbnail-width-extra-large;
            border-radius: Palette.thumbnail-border-radius;
            border-color: Palette.thumbnail-border-color;
            border-width: Palette.thumbnail-border-width;
            clip: true;
            Image {
                width: Palette.thumbnail-width-extra-large;
                height: Palette.thumbnail-width-extra-large;
                source: @image-url("../images/light.png");
            }
        }
        VerticalLayout {
            alignment: start;
            Text {
                text: "Artist Name";
                font-weight: Palette.font-weight-bold;
                font-size: 3rem;
            }
            Text {
                text: "in Atmospheric Black Metal, Black Metal, Drone, Hard Rock & Metal, Metal, Rock";
                font-size: 1.2rem;
            }
        }
    }
}