import { Button, VerticalBox , ScrollView} from "std-widgets.slint";
import { Card, CardModel } from "card.slint";

export struct CardGridModel {
    cards: [CardModel],
}

export component CardGrid inherits ScrollView {
    callback navigate(string);

    in-out property <CardGridModel> model: {
        cards: [
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
        ]
    };

    // TODO this is causing a lot of problems; seems to be a race condition
    // where as the cols changes when resizing it causing a brief lockup.
    // Oh, looks like it only happens when resizing with mouse, not with a
    // window action. So maybe events overloading.
    property <int> cols: Math.floor(self.width / 1px / 270);

    VerticalLayout {
        spacing: 20px;
        for row in Math.ceil(model.cards.length / cols): HorizontalLayout {
            alignment: center;
            spacing: 20px;
            for col in cols: Card {
                 model: model.cards[row * cols + col];
                 navigate(url) => { root.navigate(url); }
            }
        }
    }
}
