import { Button, VerticalBox , ScrollView} from "std-widgets.slint";

// TODO can this just be properties of the Card? Can I create cards in the Rust
// code? Cause then I could set colors and all and that would be cool.
export struct CardModel {
    image: image,
    title: string,
    // TODO eventually subtitles as they will all be links to artists.
    sub-title: string,
    url: string,
}

export component Card inherits VerticalLayout {
    width: 250px;
    spacing: 2px;

    in property <CardModel> model: {
        image: @image-url("../images/dark.png"),
        title: "A Reign of Fish",
        sub-title: "Fresh Pliers",
        url: "internal://1231792128374089732402",
    };
    in property <string> url;

    callback image-clicked(string);
    callback title-clicked(string);
    callback sub-title-clicked(string);

    alignment: start;

    image-area := TouchArea {
        width: 250px;
        height: 250px;
        mouse-cursor: pointer;
        clicked => { root.image-clicked(root.url); }
        Rectangle {
            width: 100%;
            height: 100%;
            border-radius: 5px;
            clip: true;
            Image {
                width: 100%;
                height: 100%;
                source: model.image;
            }    
        }
    }
    Rectangle {}
    title-area := TouchArea {
        mouse-cursor: pointer;
        clicked => { root.title-clicked(root.url); }
        title := Text {
            font-weight: 600;
            text: model.title;
        }
    }
    sub-title-area := TouchArea {
        mouse-cursor: pointer;
        clicked => { root.sub-title-clicked(root.url); }
        Text {
            text: model.sub-title;
            wrap: no-wrap;
        }
    }
}
