import { Button, VerticalBox , ScrollView} from "std-widgets.slint";

export component Card inherits VerticalLayout {
    spacing: 2px;
    Rectangle {
        border-radius: 6px;
        clip: true;
        Image {
            source: @image-url("../images/light.png");
            min-width: 250px;
            min-height: 250px;
        }    
    }
    Rectangle {
        width: 1px;
        height: 2px;
    }
    Text {
        font-weight: 900;
        text: "Focus Infinite Ring";
    }
    Text {
        color: #5d5d5d;
        text: "Jellyfish Brothers";
    }
}
