import { Button, VerticalBox , ScrollView} from "std-widgets.slint";
import { Card } from "card.slint";

// TODO the way Music does it's card image sizing is very smoove. It maintains
// a constant margin on the left and right and then keeps the images between
// about 170 and 235
export component CardGrid inherits ScrollView {
    in-out property <int> n: 1000;
    // TODO this is causing a lot of problems; seems to be a race condition
    // where as the cols changes when resizing it causing a brief lockup.
    // Oh, looks like it only happens when resizing with mouse, not with a
    // window action. 
    in-out property <int> cols: Math.floor(self.width / 1px / 270);

    VerticalLayout {
        spacing: 20px;
        alignment: center;
        for row in Math.ceil(n / cols): HorizontalLayout {
            spacing: 20px;
            for col in cols: Card {
    
            }
        }
    }
}
