import { Button, VerticalBox , ScrollView} from "std-widgets.slint";
import { Card, CardModel } from "card.slint";
import { Palette, Navigator } from "common.slint";
import {StyleMetrics} from "std-widgets.slint";

export struct CardGridModel {
    cards: [CardModel],
}

export component CardGrid inherits ScrollView {
    in-out property <CardGridModel> model: {
        cards: [
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/dark.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
            {
                image: {image: @image-url("../images/light.png"),name: "A Reign of Fish",url: "dimple://releases/1234"},
                title: {name: "A Reign of Fish",url: "dimple://releases/1234"},
                sub-title: {name: "Fresh Pliers",url: "dimple://artists/9876"},
            },
        ]
    };

    property <int> cols: Math.floor((self.width - StyleMetrics.layout-padding) / (Palette.thumbnail-width-large + StyleMetrics.layout-spacing));

    property <bool> last_row;
    VerticalLayout {
        spacing: StyleMetrics.layout-spacing;
        padding-right: StyleMetrics.layout-padding;
        alignment: start;
        for row in Math.ceil(model.cards.length / cols): HorizontalLayout {
            alignment: space-between;
            spacing: StyleMetrics.layout-spacing;
            for col in Math.min(cols, model.cards.length - Math.floor(model.cards.length / cols)): Card {
                 model: model.cards[row * cols + col];
            }
        }
    }
}
