import { Button, VerticalBox , ScrollView} from "std-widgets.slint";

// TODO can this just be properties of the Card? Can I create cards in the Rust
// code? Cause then I could set colors and all and that would be cool.
export struct CardModel {
    image: image,
    title: string,
    // TODO eventually subtitles as they will all be links to artists.
    sub-title: string,
}

export component Card inherits VerticalLayout {
    width: 250px;
    spacing: 2px;

    in property <CardModel> model;
    
    Rectangle {
        width: 250px;
        height: 250px;
        border-radius: 6px;
        clip: true;
        Image {
            width: 250px;
            height: 250px;
            source: model.image;
        }    
    }
    Rectangle {}
    Text {
        font-weight: 900;
        text: model.title;
    }
    Text {
        color: #5d5d5d;
        text: model.sub-title;
    }
}
