import { StyleMetrics , VerticalBox} from "std-widgets.slint";

export global Styles  {
    in-out property<int> font-weight-bold: 700;

    in-out property<length> thumbnail-width-sidebar: 48px;

    in-out property<length> icon-width-sidebar: 24px;

    in-out property<length> thumbnail-width-small: 70px;
    in-out property<length> thumbnail-width-medium: 120px;
    in-out property<length> thumbnail-width-large: 200px;
    in-out property<length> thumbnail-width-extra-large: 275px;
    in-out property<length> thumbnail-border-radius: 5px;
    in-out property<length> thumbnail-border-width: 1px;
    in-out property<color> thumbnail-border-color: StyleMetrics.default-text-color;

    in-out property<color> link-color: StyleMetrics.default-text-color;
    in-out property<color> link-color-hover: StyleMetrics.default-text-color.mix(blue, 0.60);

    in-out property<color> icon-color: self.link-color;
    in-out property<color> icon-color-hover: self.link-color-hover;

    in-out property <length> default_font_size: 14px;

    in-out property <float> page_title_font_rem: 3;
    in-out property <float> section_font_rem: 2;

}

export global Navigator {
    callback navigate(string);
    callback url() -> string;
    in-out property <bool> busy;
}

export global AppState {
    in-out property <bool> online: true;
    in-out property <bool> debug: false;

    callback player_previous();
    callback player_play_pause();
    callback player_next();
    callback player_seek(int);
}
