export global Palette  {
    in-out property<string> font-family-default: "Manrope";
    
    in-out property<color> text-color-default: #000;
    in-out property<color> text-color-title: #272727;
    in-out property<color> text-color-sub-title: #272727;

    in-out property<int> font-weight-default: 400;
    in-out property<int> font-weight-title: 600;
    in-out property<int> font-weight-sub-title: 400;

    in-out property<length> font-size-default: 15px;
    in-out property<length> font-size-small: 11px;
    in-out property<length> font-size-medium: 15px;
    in-out property<length> font-size-large: 26px;

    in-out property<length> image-width-small: 70px;
    in-out property<length> image-width-medium: 120px;
    in-out property<length> image-width-large: 250px;
    in-out property<length> image-width-extra-large: 275px;

    in-out property<length> image-border-radius: 5px;
}

export global Navigator {
    callback navigate(string);
}

export struct Link {
    name: string,
    url: string,
}

export struct ImageLink {
    image: image,
    name: string,
    url: string,
}


