import { Button, LineEdit, HorizontalBox } from "std-widgets.slint";
import { Palette } from "common.slint";

export component NavBar inherits HorizontalBox {
    vertical-stretch: 0;
    // spacing: 8px;
    // height: 46px;
    in property <length> icon-height: 24px;
    in property <length> icon-width: 24px;
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/house.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/vinyl-record.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/music-notes.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/playlist.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/globe-simple.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/clock-counter-clockwise.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/queue.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Rectangle {
        horizontal-stretch: 1;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/arrow-left.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/arrow-right.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/arrow-clockwise.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
    LineEdit {
        horizontal-stretch: 1;
        placeholder-text: "Search...";
        // TODO change back to edited when better handling in the search function
        // accepted(query) => { Navigator.navigate("dimple://search/" + query); }
        font-size: 1.3rem;
        height: 3.0rem;
    }
    Image {
        source: @image-url("../icons/phosphor/SVGs/regular/gear.svg");
        width: icon-height;
        height: icon-width;
        colorize: Palette.icon-color;
    }
}

