import { HorizontalBox, LineEdit, Palette, Button } from "std-widgets.slint";
import { Styles, Navigator, AppState } from "./common.slint";
import { Label } from "common.slint";
import { SettingsAdapter } from "pages/settings.slint";
import { SearchResultsAdapter } from "pages/search_results.slint";

component NavBarButton inherits TouchArea {
    in property <image> source;
    width: image.width;
    Rectangle {
        background: root.has-hover ? Palette.accent-background : Palette.background;
        border-radius: Styles.thumbnail-border-radius;
        image := Image {
            source: root.source;
            colorize: root.has-hover ? Palette.accent-foreground : Palette.foreground;
            width: 24px;
            height: 24px;
        }
    }
}

export component NavBar inherits HorizontalBox {
    padding: 0;
    NavBarButton {
        source: @image-url("../icons/phosphor/SVGs/regular/sidebar-simple.svg");
        clicked => { 
            SettingsAdapter.set_sidebar_open(!SettingsAdapter.sidebar-open); 
        }
    }
    NavBarButton {
        source: @image-url("../icons/phosphor/SVGs/regular/queue.svg");
        clicked => { Navigator.navigate("dimple://queue") }
    }
    Rectangle {
        width: parent.spacing;
    }
    NavBarButton {
        source: @image-url("../icons/phosphor/SVGs/regular/arrow-left.svg");
        clicked => { Navigator.navigate("dimple://back") }
    }
    NavBarButton {
        source: @image-url("../icons/phosphor/SVGs/regular/arrow-right.svg");
        clicked => { Navigator.navigate("dimple://forward") }
    }
    NavBarButton {
        source: @image-url("../icons/phosphor/SVGs/regular/arrow-clockwise.svg");
        clicked => { Navigator.navigate("dimple://refresh") }
    }
    NavBarButton {
        source: @image-url("../icons/phosphor/SVGs/regular/house.svg");
        clicked => { Navigator.navigate("dimple://home") }
    }
    LineEdit {
        placeholder-text: "Search for songs, artists, genres, playlists, URLs...";
        // edited(query) => { SearchResultsAdapter.query(query); }
        accepted(query) => { SearchResultsAdapter.query(query); }
        font-size: Styles.default-font-size;
        height: self.font-size * 2;
    }
}
