import { Slider , GroupBox, HorizontalBox} from "std-widgets.slint";
import { Palette } from "common.slint";
import { StyleMetrics } from "std-widgets.slint";

component InfoAreaLabel inherits HorizontalLayout {
    spacing: 4px;

    in property <image> icon;
    in property <string> text;
    in property <float> font-weight;

    Image {
        source: icon;
        height: 1.5rem;
        width: 1.5rem;
        colorize: StyleMetrics.default-text-color;
    }
    Text {
        text: text;
        vertical-alignment: top;
        font-size: 1.5rem;
        font-weight: font-weight;
    }
}

export component PlayerBar {
    in property <image> current-image;
    in property <string> current-title;
    in property <string> current-release;
    in property <string> current-artist;

    HorizontalLayout {
        spacing: StyleMetrics.layout-spacing * 2;
        Rectangle {
            width: img.width;
            height: img.height;
            border-radius: Palette.thumbnail-border-radius;
            border-width: Palette.thumbnail-border-width;
            border-color: Palette.thumbnail-border-color;
            clip: true;
            img := Image {
                source: @image-url("../images/dark.png");
                width: Palette.thumbnail-width-medium;
                height: Palette.thumbnail-width-medium;
            }    
        }
        Rectangle {
            horizontal-stretch: 1;
            clip: true;
            VerticalLayout {
                spacing: 2px;
                InfoAreaLabel {
                    icon: @image-url("../icons/phosphor/SVGs/bold/music-notes-bold.svg");
                    text: "Trap Party in the Trap House";
                    font-weight: Palette.font-weight-bold;
                }
                InfoAreaLabel {
                    icon: @image-url("../icons/phosphor/SVGs/regular/vinyl-record.svg");
                    text: "Trappin' in Kawaii 2023";
                }
                InfoAreaLabel {
                    icon: @image-url("../icons/phosphor/SVGs/regular/users-three.svg");
                    text: "Grid of Benjamins";
                }
                Rectangle {
                    vertical-stretch: 1;
                }
                Slider { 
                    value: 42;
                    vertical-stretch: 0;
                }
                HorizontalLayout {
                    Text {
                        text: "09:30";
                        font-size: 0.8rem;
                    }
                    Text {
                        horizontal-alignment: right;
                        text: "09:30";
                        font-size: 0.8rem;
                    }
                }
            }
        }
        VerticalLayout {
            alignment: start;
            spacing: 2px;
            width: inner_rect.width * 1.5;
            HorizontalLayout {
                alignment: center;
                inner_rect := Rectangle {
                    width: inner_img.width;
                    height: inner_img.height;
                    border-radius: Palette.thumbnail-border-radius;
                    border-width: Palette.thumbnail-border-width;
                    border-color: Palette.thumbnail-border-color;
                    clip: true;
                    inner_img := Image {
                        source: @image-url("../images/light.png");
                        width: Palette.thumbnail-width-small;
                        height: Palette.thumbnail-width-small;
                    }    
                }
            }
            Text {
                horizontal-alignment: center;
                text: "Finality Season";
                wrap: word-wrap;
                overflow: elide;
                font-size: 0.8rem;
                max-height: 3rem;
            }
            Text {
                horizontal-alignment: center;
                text: "The Frigid Depths of the Heart of the Kit-Kat CEO";
                wrap: word-wrap;
                overflow: elide;
                font-size: 0.8rem;
                max-height: 3rem;
            }
        }
    }
}
