import { HorizontalBox } from "std-widgets.slint";
import { Palette } from "common.slint";

export struct ReleaseDetailsModel {

}

export component ReleaseDetails inherits VerticalLayout {
    alignment: start;
    HorizontalLayout {
        spacing: 10px;
        alignment: start;
        Rectangle {
            width: Palette.image-width-extra-large;
            height: Palette.image-width-extra-large;
            border-radius: Palette.image-border-radius;
            clip: true;
            drop-shadow-blur: 4px;
            drop-shadow-color: #000;
            drop-shadow-offset-y: 1px;
            Image {
                width: Palette.image-width-extra-large;
                height: Palette.image-width-extra-large;
                source: @image-url("../images/dark.png");
            }
        }
        VerticalLayout {
            alignment: start;
            spacing: 2px;
            Text {
                font-size: Palette.font-size-large;
                font-weight: Palette.font-weight-title;
                color: Palette.text-color-title;
                text: "Release Name";
            }
            Text {
                font-size: Palette.font-size-large;
                font-weight: Palette.font-weight-sub-title;
                color: Palette.text-color-sub-title;
                text: "Artist Name";
            }
            Text {
                text: "in Atmospheric Black Metal, Black Metal, Drone, Hard Rock & Metal, Metal, Rock";
            }
        }
    }
}