import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { Palette, Link, Navigator, Links , Linnk} from "common.slint";
import { CardModel } from "card.slint";
import { StyleMetrics , ScrollView, ListView} from "std-widgets.slint";
import { CardGrid } from "card_grid.slint";

export struct ReleaseGroupDetailsModel {
    card: CardModel,
    disambiguation: string,
    summary: string,
    genres: [Link],
    releases: [CardModel],
    links: [Link],
}

export component ReleaseGroupDetails inherits ScrollView {
    VerticalBox {
        alignment: start;
        spacing: StyleMetrics.layout-spacing * 2;
        // Header
        HorizontalLayout {
            alignment: start;
            spacing: StyleMetrics.layout-spacing;
            Rectangle {
                width: Palette.thumbnail-width-extra-large;
                height: Palette.thumbnail-width-extra-large;
                border-radius: Palette.thumbnail-border-radius;
                border-color: Palette.thumbnail-border-color;
                border-width: Palette.thumbnail-border-width;
                clip: true;
                Image {
                    width: Palette.thumbnail-width-extra-large;
                    height: Palette.thumbnail-width-extra-large;
                    source: model.card.image.image;
                }
            }
            VerticalLayout {
                alignment: start;
                spacing: StyleMetrics.layout-spacing;
                HorizontalLayout {
                    alignment: start;
                    spacing: StyleMetrics.layout-spacing;
                    Image {
                        // TODO DRY
                        source: @image-url("../icons/phosphor/SVGs/regular/vinyl-record.svg");
                        height: 4rem;
                        width: 4rem;
                        colorize: StyleMetrics.default-text-color;
                    }
                    Text {
                        text: model.card.title.name;
                        font-weight: Palette.font-weight-bold;
                        font-size: 4rem;
                    }
                }
                HorizontalLayout {
                    alignment: start;
                    Text {
                        text: "In ";
                        font-size: 1.3rem;
                    }    
                    Links {
                        links: model.genres;
                    }
                }
                Text {
                    text: model.summary;
                    wrap: word-wrap;
                    font-size: 1.2rem;
                }
            }
        }

        // Releases
        if model.releases.length > 0: VerticalLayout {
            Text {
                text: "Releases";
                font-weight: Palette.font-weight-bold;
                font-size: 2rem;
            }
            CardGrid {
                cards: model.releases;
                parent-width: root.width;
            }
        }

        // Links
        if model.links.length > 0: VerticalLayout {
            Text {
                text: "Links";
                font-weight: Palette.font-weight-bold;
                font-size: 2rem;
            }
            for link in model.links: Linnk {
                url: link.url;
                name: link.name;
            }
        }
    }

    in property <ReleaseGroupDetailsModel> model;
}
