[package]
name = "hello_world"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false

[dependencies]
eframe = "0.21.3"
egui_extras = { version = "0.21.0", features = ["image"] }
image = { version = "0.24.5", features = ["jpeg", "png"] }
rand = "0.8.5"
reqwest = "0.11.14"
tracing-subscriber = "0.3"
catppuccin-egui = "2.0"