[package]
name = "dimple"
version = "0.1.0"
authors = ["Jason von Nieda <jason@vonnieda.org>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false
default-run = "dimple"

[dependencies]
eframe = "0.21.3"
egui_extras = { version = "0.21.0", features = ["image"] }
image = { version = "0.24.5", features = ["jpeg", "png"] }
tracing-subscriber = "0.3"
catppuccin-egui = "2.0"
sunk = { path = "lib/sunk" }
config = "0.13.3"
threadpool = "1.8.1"
fuzzy-matcher = "*"
sled = "0.34.7"
bincode = "1.3.3"
serde = "1.0.158"
rayon = "1.7.0"
