[package]
name = "dimple"
version = "0.1.0"
authors = ["Jason von Nieda <jason@vonnieda.org>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false
default-run = "dimple"

[dependencies]
catppuccin-egui = "2.0"
config = "0.13.3"
eframe = "0.21.3"
egui_extras = { version = "0.21.0", features = ["image"] }
env_logger = "0.10.0"
fuzzy-matcher = "*"
image = { version = "0.24.5", features = ["jpeg", "png"] }
log = "0.4.17"
sunk = { path = "lib/sunk" }
sled = "0.34.7"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
symphonia = { version = "0.5.2", features = ["all"] }
walkdir = "2.3.3"
url = "2.3.1"
rodio = { version = "0.17.1" }
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
rayon = "1.7.0"


