[workspace]
members = [
    "dimple_core",
    "dimple_core_macro",
    "dimple_ui_slint", 
    "dimple_data",
]
resolver="2"

[profile.release]
debug = true

[profile.dev]
split-debuginfo = "unpacked"


