[workspace]
members = [
    "dimple_core",
    "dimple_librarian",
    "dimple_librarian_tests",
    "dimple_ui_slint",
    "dimple_cli", 
    "dimple_core_macro",
]
resolver="2"

[profile.release]
debug = true

[profile.dev]
split-debuginfo = "unpacked"
