[package]
name = "hello_world"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false

[dependencies]
eframe = "0.21.3"
egui_extras = { version = "0.21.0", features = ["image"] }
image = { version = "0.24.5", features = ["jpeg", "png"] }
rand = "0.8.5"
tracing-subscriber = "0.3"
catppuccin-egui = "2.0"
ehttp = "0.2.0"
#sunk = "0.1.2"
sunk = { path = "lib/sunk" }
config = "0.13.3"
threadpool = "1.8.1"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
