[package]
name = "dimple_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.5", features = ["jpeg", "png"] }
serde = { version = "1.0.158", features = ["derive"] }
sled = "0.34.7"
musicbrainz_rs = { version = "0.5.0", default-features = false, features = ["blocking"] }
ulid = "1.1.0"
log = "0.4.19"
