ALTER TABLE Track ADD COLUMN media_position INT DEFAULT NULL;
ALTER TABLE Track ADD COLUMN discogs_id TEXT DEFAULT NULL;
ALTER TABLE Track ADD COLUMN lastfm_id TEXT DEFAULT NULL;

ALTER TABLE MediaFile ADD COLUMN release_date TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN isrc TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN label TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN original_date TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN original_year TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN website TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN total_discs INT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN disc_number INT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN disc_subtitle TEXT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN total_tracks INT DEFAULT NULL;
ALTER TABLE MediaFile ADD COLUMN track_number INT DEFAULT NULL;
