[package]
name = "dimple_ui_slint"
version = "0.1.0"
authors = ["Jason von Nieda <jason@vonnieda.org>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
slint = "1.1.1"
env_logger = "0.10.0"
dimple_core = { path = "../dimple_core" }
dimple_player = { path = "../dimple_player" }
dimple_sled_library = { path = "../dimple_sled_library" }
dimple_folder_library = { path = "../dimple_folder_library" }
dimple_navidrome_library = { path = "../dimple_navidrome_library" }
dimple_s3_compatible_storage_library = { path = "../dimple_s3_compatible_storage_library" }
dimple_librarian = { path = "../dimple_librarian" }
serde = "1.0.175"
config = "0.13.3"
image = "0.24.6"
num-complex = "0.4.3"
rand = "0.8.5"

[build-dependencies]
slint-build = "1.1"
