import { ScrollView } from "std-widgets.slint";
import { CardGrid, CardGridAdapter, LazyCardGrid, LazyCardGridAdapter } from "../components/card_grid.slint";

export component ArtistList inherits VerticalLayout {
    in-out property <LazyCardGridAdapter> model;

    ScrollView {                        
        card-grid := LazyCardGrid {
            cards: model.cards;
            parent-width: parent.width;
        }
    }
    Text {
        horizontal-alignment: right;
        text: model.cards.length + " items";
    }
}