import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import { CardAdapter, Card } from "../components/card.slint";
import {Styles} from "../common.slint";

export component ArtistList inherits VerticalBox {
    in-out property <CardGridAdapter> model: model_ph;

    Text { 
        text: "Artists";
        font-size: 1rem * Styles.page_title_font_rem;
    }
    ScrollView {        
        vertical-scrollbar-policy: always-on;
        horizontal-scrollbar-policy: always-off;
        viewport-width: parent.width;
        VerticalBox {
            card-grid := CardGrid {
                cards: model.cards;
                parent-width: root.width;
            }
        }
    }
    Text {
        horizontal-alignment: right;
        text: model.cards.length + " items";
    }

    property <CardAdapter> card_ph: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
    };
    
    property <[CardAdapter]> cards_ph: [card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph];
    // property <[CardAdapter]> cards_ph: [card_ph, card_ph, card_ph, card_ph, card_ph, card_ph];

    property <CardGridAdapter> model_ph: {
        cards: cards_ph,
    };
}