import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import {Styles} from "../common.slint";

export component ArtistList inherits VerticalBox {
    in-out property <CardGridAdapter> model;

    Text { 
        text: "Artists";
        font-size: 1rem * Styles.page_title_font_rem;
    }
    ScrollView {                        
        card-grid := CardGrid {
            cards: model.cards;
            parent-width: parent.width;
        }
    }
    Text {
        horizontal-alignment: right;
        text: model.cards.length + " items";
    }
}