import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { AppState } from "../common.slint";

export global EventListAdapter {
    in property <[[StandardListViewItem]]> row_data;
    pure callback sort_model([[StandardListViewItem]], int, bool) -> [[StandardListViewItem]];
    pure callback current_row_changed(int);
}
 
export component EventList inherits VerticalLayout {
    property <int> sort-index: -1;
    property <bool> sort-acending;
        
    StandardTableView {
        vertical-stretch: 1;
        horizontal-stretch: 1;
        columns: [
            { title: "Date" },
            { title: "Type" },
            { title: "Artist" },
            { title: "Album" },
            { title: "Title" },
        ];
        rows: EventListAdapter.sort_model(EventListAdapter.row_data, root.sort-index, root.sort-acending);
        current-row-changed(row) => { 
            EventListAdapter.current_row_changed(row);
        }
        sort-ascending(index) => {
            root.sort-index = index;
            root.sort-acending = true;
        }
        sort-descending(index) => {
            root.sort-index = index;
            root.sort-acending = false;
        }        
    }
    Text {
        horizontal-alignment: right;
        text: EventListAdapter.row_data.length + " items";
    }
}
