import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import {CardAdapter} from "../components/card.slint";
import {Styles, Label, PageSubtitle, PageTitle} from "../common.slint";

export component GenreList inherits ScrollView {
    in-out property <CardGridAdapter> model: model_ph;

    VerticalBox {
        width: 100%;
        alignment: start;
        padding: 0;

        VerticalLayout {
            PageTitle { 
                text: "Genres";
            }
            PageSubtitle {
                text: model.cards.length + " items";
            }
        }
        CardGrid {
            cards: model.cards;
        }
    }

    property <CardAdapter> card_ph: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Mega-Super-Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Super Mega Ultra Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Finger Lickin' Good Pliers",url: "internal://artist/9876"},
    };
    
    property <[CardAdapter]> cards_ph: [card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph];

    property <CardGridAdapter> model_ph: {
        cards: cards_ph,
    };
}