import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import {Styles, Texxt} from "../common.slint";

export component GenreList inherits VerticalBox {
    in-out property <CardGridAdapter> model;

    Texxt {
        text: "Genres";
    }
    ScrollView {        
        vertical-scrollbar-policy: always-on;
        horizontal-scrollbar-policy: always-off;
        viewport-width: parent.width;
        VerticalBox {
            card-grid := CardGrid {
                cards: model.cards;
                parent-width: root.width;
            }
        }
    }
    Texxt {
        horizontal-alignment: right;
        text: model.cards.length + " items";
    }
}