import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardGridAdapter, VirtualCardGrid } from "../components/card_grid.slint";
import {CardAdapter} from "../components/card.slint";
import {Styles, Label, PageSubtitle, PageTitle} from "../common.slint";

export global GenreListAdapter {
    in-out property <[CardAdapter]> cards: [{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },];
}

export component GenreList inherits VerticalBox {
    padding: 0;
    
    VerticalLayout {
        PageTitle { 
            text: "Genres";
        }
        PageSubtitle {
            text: GenreListAdapter.cards.length + " items";
        }
    }
    VirtualCardGrid {
        cards: GenreListAdapter.cards;
        card-placeholder: @image-url("../../icons/phosphor/PNGs/regular/globe-simple.png");
    }

    property <CardAdapter> card_ph: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Mega-Super-Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Super Mega Ultra Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Finger Lickin' Good Pliers",url: "internal://artist/9876"},
    };
    
    property <[CardAdapter]> cards_ph: [card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph];

    property <CardGridAdapter> model_ph: {
        cards: cards_ph,
    };
}