import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { LinkAdapter, Links, Link, LinkButtons} from "../components/link.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, ListView, Button} from "std-widgets.slint";
import { CardGrid, CardSectionAdapter } from "../components/card_grid.slint";
import { Styles, Navigator, AppState, Label, PageTitle, PageSubtitle, SectionTitle, SectionSubtitle } from "../common.slint";
import { Tag } from "../components/tag.slint";
import { PopupMenu, PopupMenuButton } from "../components/popup_menu.slint";
import { BorderImage } from "../components/border_image.slint";

export global GenreDetailsAdapter {
    in property <string> key;
    in property <CardAdapter> card: {
                image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
                title: {name: "A Reign of Fish"},
            };
    in property <string> disambiguation: "Not to be confused with Rain of Fish by Fargo.";
    in property <string> summary: "Fresh Pliers does it again with 'A Reign of Fish'. Ex nostrud culpa id veniam aliqua aliqua ipsum. Velit do id amet labore mollit id cillum commodo Lorem proident labore eu. Incididunt minim irure culpa excepteur officia sit consequat est mollit. Ipsum anim anim sunt dolore. Laborum consequat deserunt laboris ullamco cillum. Ullamco deserunt ut quis dolore aliquip esse consequat velit amet. Nulla tempor veniam dolor amet occaecat adipisicing nulla laboris.\n\nQui non irure anim irure nisi nulla ex aliquip. Sit do irure esse magna sit do eiusmod. Anim commodo velit non enim nulla.\n\nAnim incididunt dolore nulla laboris eu mollit Lorem minim reprehenderit in quis magna mollit. Labore Lorem esse anim ipsum esse irure ipsum proident deserunt officia consequat sunt sit. Ex laborum ipsum laboris nisi proident. Nulla culpa est commodo dolor. Magna sint id et ut esse mollit qui elit voluptate ea.";
    in property <[LinkAdapter]> links: [{name: "https://bandcamp.com/arof",url: "internal://release/1234"}];
    in property <string> dump;
    in-out property <[CardSectionAdapter]> sections: [
        { title: "For You", sub-title: "From your listens.", cards: [
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "A Thing With Super Ultra Mega Stuff"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "A Thing With Super Ultra Mega Stuff"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "A Thing With Super Ultra Mega Stuff"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "A Thing With Super Ultra Mega Stuff"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
        ]},
        { title: "Recents", cards: [
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
        ]},
        { title: "New Releases", cards: [
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
        ]},
        { title: "Popular", sub-title: "With other MusicBrainz listeners.", cards: [
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
        ]},
        { title: "Old Favorites", cards: [
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
            { image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"}},
        ]},
    ];
}

export component GenreDetails inherits ScrollView {
    horizontal-scrollbar-policy: always-off;
    
    VerticalBox {
        width: 100%;
        alignment: start;
        padding: 0;
        
        HorizontalBox {
            alignment: start;
            padding: 0;

            BorderImage {
                width: Styles.thumbnail-width-extra-large;
                height: Styles.thumbnail-width-extra-large;
                source: GenreDetailsAdapter.card.image.image;
            }
            VerticalBox {
                alignment: start;
                padding: 0;

                VerticalLayout {
                    PageTitle {
                        text: GenreDetailsAdapter.card.title.name;
                    }
                    if GenreDetailsAdapter.disambiguation != "": PageSubtitle {
                        text: GenreDetailsAdapter.disambiguation;
                    }
                }
                // LinkButtons {
                //     links: GenreDetailsAdapter.links;
                //     height: self.preferred-height;
                // }
                if GenreDetailsAdapter.summary != "": Label {
                    text: GenreDetailsAdapter.summary;
                    wrap: word-wrap;
                }
            }
        }

        // if GenreDetailsAdapter.releases.length > 0: VerticalBox {
        //     alignment: start;
        //     padding: 0;
        //     SectionTitle {
        //         text: "Releases";
        //     }
        //     CardGrid {
        //         cards: GenreDetailsAdapter.releases;
        //     }
        // }

        for section in GenreDetailsAdapter.sections: VerticalBox {
            alignment: start;
            padding: 0;
            padding-bottom: 16px;
            VerticalLayout {
                SectionTitle {
                    text: section.title;
                }
                if section.sub-title != "": SectionSubtitle {
                    text: section.sub-title;
                }
            }
            CardGrid {
                cards: section.cards;
                max-rows: 1;
            }
        }

        if GenreDetailsAdapter.links.length > 0: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Links";
            }
            for link in GenreDetailsAdapter.links: Link {
                url: link.url;
                name: link.name;
            }
        }        
    }
}


