import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { AppState } from "../common.slint";
import {Styles, Texxt} from "../common.slint";

export global HistoryListAdapter {
    in property <[[StandardListViewItem]]> row_data;
    pure callback sort_model([[StandardListViewItem]], int, bool) -> [[StandardListViewItem]];
    pure callback current_row_changed(int);
}
 
export component HistoryList inherits VerticalBox {
    property <int> sort-index: -1;
    property <bool> sort-acending;
        
    Texxt {
        text: "Listening History";
    }

    StandardTableView {
        vertical-stretch: 1;
        horizontal-stretch: 1;
        columns: [
            { title: "Date", horizontal_stretch: 0.15 },
            { title: "Type", horizontal_stretch: 0.15 },
            { title: "Artist", horizontal_stretch: 0.20 },
            { title: "Album", horizontal_stretch: 0.20 },
            { title: "Title", horizontal_stretch: 0.30 },
        ];
        rows: HistoryListAdapter.sort_model(HistoryListAdapter.row_data, root.sort-index, root.sort-acending);
        current-row-changed(row) => { 
            HistoryListAdapter.current_row_changed(row);
        }
        sort-ascending(index) => {
            root.sort-index = index;
            root.sort-acending = true;
        }
        sort-descending(index) => {
            root.sort-index = index;
            root.sort-acending = false;
        }        
    }
    
    Texxt {
        horizontal-alignment: right;
        text: HistoryListAdapter.row_data.length + " items";
    }
}
