import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import { Styles } from "../common.slint";
import { LinkAdapter } from "../components/link.slint";

export struct HomeSectionAdapter {
    title: string,
    cards: [CardAdapter],    
}

export struct HomeAdapter {
    sections: [HomeSectionAdapter],
    cards: [CardAdapter],
}

export component Home inherits VerticalBox {
    in-out property <HomeAdapter> model;

    Text {
        text: "Home";
        font-size: 1rem * Styles.page_title_font_rem;
    }

    for section in model.sections: VerticalLayout {
        Text {
            text: section.title;
            font-size: 1rem * Styles.section_font_rem;
        }
        ScrollView {                        
            CardGrid {
                cards: section.cards;
                parent-width: parent.width;
            }
        }
    }
}