import { ScrollView, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { CardGrid, CardGridAdapter, VirtualCardGrid } from "../components/card_grid.slint";
import { CardAdapter } from "../components/card.slint";
import {Styles, Label, PageTitle, PageSubtitle} from "../common.slint";

export global PlaylistListAdapter {
    in-out property <[CardAdapter]> cards: [
        card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, 
        card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph,
        card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph,
        card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph,
        card_ph, card_ph, card_ph, card_ph, card_ph, card_ph, card_ph,
    ];

    pure callback new_playlist();

    property <CardAdapter> card_ph: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Mega-Super-Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Super Mega Ultra Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Finger Lickin' Good Pliers",url: "internal://artist/9876"},
    };
}

export component PlaylistList inherits VerticalBox {
    VerticalLayout {
        PageTitle { 
            text: "Playlists";
        }
        PageSubtitle {
            text: PlaylistListAdapter.cards.length + " items";
        }
        // ActionButtons {
        //     ActionButton {
        //         label: @tr("New Playlist");
        //         icon: @image-url("../../icons/phosphor/SVGs/regular/plus.svg");
        //         clicked => { PlaylistListAdapter.new_playlist(); }
        //     }
        // }
    }
    VirtualCardGrid {
        cards: PlaylistListAdapter.cards;
    }
}