import { ScrollView, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import {Styles} from "../common.slint";
import { ActionButton, ActionButtons } from "../components/action_buttons.slint";

export global PlaylistListAdapter {
    pure callback new_playlist();
}

export component PlaylistList inherits VerticalBox {
    in-out property <CardGridAdapter> model;

    VerticalLayout {
        Text {
            text: "Playlists";
            font-size: 1rem * Styles.page_title_font_rem;
        }    
        ActionButtons {
            ActionButton {
                label: @tr("New Playlist");
                icon: @image-url("../../icons/phosphor/SVGs/regular/plus.svg");
                clicked => { PlaylistListAdapter.new_playlist(); }
            }
        }
    }

    ScrollView {        
        vertical-scrollbar-policy: always-on;
        horizontal-scrollbar-policy: always-off;
        viewport-width: parent.width;
        VerticalBox {
            card-grid := CardGrid {
                cards: model.cards;
                parent-width: root.width;
            }
        }
    }

    Text {
        horizontal-alignment: right;
        text: model.cards.length + " items";
    }
}