import { ScrollView, VerticalBox } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";

export component ReleaseList inherits VerticalBox {
    in-out property <CardGridAdapter> model;

    Text {
        text: "Albums";
        font-size: 3rem;
    }
    ScrollView {                        
        card-grid := CardGrid {
            cards: model.cards;
            parent-width: parent.width;
        }
    }
    Text {
        horizontal-alignment: right;
        text: model.cards.length + " items";
    }
}