import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, Button} from "std-widgets.slint";
import { LinkAdapter, Links, Link} from "../components/link.slint";
import { Styles, Navigator, AppState, Label, PageTitle, PageSubtitle, SectionTitle } from "../common.slint";
import { Tag, TagList } from "../components/tag.slint";
import { BorderImage } from "../components/border_image.slint";
import { SettingsAdapter } from "settings.slint";
import { CardGrid } from "../components/card_grid.slint";

export global ReleaseGroupDetailsAdapter {
    in property <string> key;
    in property <string> primary-type;
    in property <[string]> secondary-types;
    in property <string> first-release-date;
    in property <CardAdapter> card;
    in property <string> disambiguation;
    in property <string> summary;
    in property <[LinkAdapter]> genres;
    in property <[LinkAdapter]> links;
    in property <[LinkAdapter]> artists;
    in property <[CardAdapter]> releases;
    in property <string> dump;
    in property <bool> save;

    pure callback toggle_heart();
}

export component ReleaseGroupDetails inherits ScrollView {
    horizontal-scrollbar-policy: always-off;

    VerticalBox {
        width: 100%;
        alignment: start;
        padding: 0;

        HorizontalBox {
            padding: 0;

            VerticalLayout {
                BorderImage {
                    width: Styles.thumbnail-width-extra-large;
                    height: Styles.thumbnail-width-extra-large;
                    key: ReleaseGroupDetailsAdapter.key;
                    placeholder: @image-url("../../icons/phosphor/SVGs/regular/vinyl-record.svg");
                }
                HorizontalBox {
                    padding-left: 0;
                    padding-right: 0;
                    alignment: space-between;
                    Button {
                        icon: @image-url("../../icons/phosphor/SVGs/regular/play.svg");
                        colorize-icon: true;
                        clicked => { AppState.play_now(ReleaseGroupDetailsAdapter.key); }
                    }
                    menu-area := ContextMenuArea {
                        Button {
                            icon: @image-url("../../icons/phosphor/SVGs/regular/dots-three.svg");
                            colorize-icon: true;
                            clicked => { menu-area.show({ x: self.width / 2, y: self.height / 2 }); }
                        }
                        Menu {
                            MenuItem {
                                title: "Play Later";
                                activated => { AppState.play_later(ReleaseGroupDetailsAdapter.key); }
                            }
                            MenuItem {
                                title: "Play Next";
                                activated => { AppState.play_next(ReleaseGroupDetailsAdapter.key); }
                            }
                            MenuItem {
                                title: "Play Now";
                                activated => { AppState.play_now(ReleaseGroupDetailsAdapter.key); }
                            }
                        }
                    }
                    Button {
                        icon: ReleaseGroupDetailsAdapter.save ? @image-url("../../icons/phosphor/SVGs/fill/heart-fill.svg")
                            : @image-url("../../icons/phosphor/SVGs/regular/heart.svg");
                        colorize-icon: true;
                        clicked => { ReleaseGroupDetailsAdapter.toggle_heart(); }
                    }
                }
            }

            VerticalBox {
                alignment: start;
                padding: 0;

                VerticalLayout {
                    PageTitle {
                        text: ReleaseGroupDetailsAdapter.card.title.name;
                    }
                    if ReleaseGroupDetailsAdapter.disambiguation != "": PageSubtitle {
                        text: ReleaseGroupDetailsAdapter.disambiguation;
                    }
                }

                HorizontalLayout {
                    Label {
                        text: "\{ReleaseGroupDetailsAdapter.primary-type} by ";
                        font-size: Styles.default-font-size * 1.1;
                    }
                    Links {
                        links: ReleaseGroupDetailsAdapter.artists;
                        height: self.preferred-height;
                        font-size: Styles.default-font-size * 1.1;
                    }
                }

                Label {
                    text: "First released \{ReleaseGroupDetailsAdapter.first-release-date}";
                    font-size: Styles.default-font-size * 1.1;
                }

                TagList {
                    tags: ReleaseGroupDetailsAdapter.genres;
                    height: self.preferred-height;
                }
                if ReleaseGroupDetailsAdapter.summary != "": Label {
                    text: ReleaseGroupDetailsAdapter.summary;
                    wrap: word-wrap;
                    font-family: Styles.text-block-font-family;
                }
            }
        }

        if ReleaseGroupDetailsAdapter.releases.length > 0: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Releases";
            }
            CardGrid {
                cards: ReleaseGroupDetailsAdapter.releases;
            }
        }

        if ReleaseGroupDetailsAdapter.releases.length == 0: VerticalBox {
            alignment: start;
            padding: 0;
            Label {
                text: "No releases added yet.";
            }
        }

        if ReleaseGroupDetailsAdapter.links.length > 0: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Links";
            }
            for link in ReleaseGroupDetailsAdapter.links: Link {
                url: link.url;
                name: link.name;
            }
        }

        if SettingsAdapter.debug: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Debug";
            }
            Text {
                text: ReleaseGroupDetailsAdapter.dump;
                wrap: word-wrap;
            }
        }
    }
}
