import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { LinkAdapter, Links, Link} from "../components/link.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView, Button, ComboBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { LinkAdapter, Links, Link, LinkButtons} from "../components/link.slint";
import { Styles, Navigator, AppState, Label, PageTitle, PageSubtitle, SectionTitle } from "../common.slint";
import { PopupMenu, PopupMenuButton } from "../components/popup_menu.slint";
import { Tag, TagList } from "../components/tag.slint";
import { BorderImage } from "../components/border_image.slint";
import { BasicTableView } from "../components/basic_table_view.slint";
import { SettingsAdapter } from "settings.slint";
import { CardGrid } from "../components/card_grid.slint";

export global ReleaseDetailsAdapter {
    in property <string> key;
    in property <string> primary-type: "Album";
    in property <[string]> secondary-types: ["Live"];
    in property <CardAdapter> card: {
                image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
                title: {name: "A Reign of Fish"},
            };
    in property <string> disambiguation: "Not to be confused with Rain of Fish by Fargo.";
    in property <string> summary: "Fresh Pliers does it again with 'A Reign of Fish'. Ex nostrud culpa id veniam aliqua aliqua ipsum. Velit do id amet labore mollit id cillum commodo Lorem proident labore eu. Incididunt minim irure culpa excepteur officia sit consequat est mollit. Ipsum anim anim sunt dolore. Laborum consequat deserunt laboris ullamco cillum. Ullamco deserunt ut quis dolore aliquip esse consequat velit amet. Nulla tempor veniam dolor amet occaecat adipisicing nulla laboris.\n\nQui non irure anim irure nisi nulla ex aliquip. Sit do irure esse magna sit do eiusmod. Anim commodo velit non enim nulla.\n\nAnim incididunt dolore nulla laboris eu mollit Lorem minim reprehenderit in quis magna mollit. Labore Lorem esse anim ipsum esse irure ipsum proident deserunt officia consequat sunt sit. Ex laborum ipsum laboris nisi proident. Nulla culpa est commodo dolor. Magna sint id et ut esse mollit qui elit voluptate ea.";
    in property <[LinkAdapter]> genres: [{name: "heavy metal"},{name: "hard rock"},{name: "acid rock"},{name: "heavy metal"},{name: "hard rock"},{name: "acid rock"},{name: "heavy metal"},{name: "hard rock"},{name: "acid rock"},];
    in property <[LinkAdapter]> links: [{name: "Spotify"},{name: "Bandcamp"},{name: "Spotify"},{name: "Bandcamp"},];
    in property <[LinkAdapter]> artists: [{name: "Fresh Pliers"},{name: "Example Band"},{name: "Teal Cup"},];
    in property <[[StandardListViewItem]]> track_items: [
        [ { text: "1" }, { text: "Rivers" }, { text: "A Reign of Fish" }, { text: "3:22" } ],
        [ { text: "2" }, { text: "Seas" }, { text: "A Reign of Fish" }, { text: "1:22" } ],
        [ { text: "3" }, { text: "Otters" }, { text: "A Reign of Fish" }, { text: "4:22" } ],
        [ { text: "4" }, { text: "Other Fish" }, { text: "A Reign of Fish" }, { text: "6:32" } ],
        [ { text: "5" }, { text: "Rocks" }, { text: "A Reign of Fish" }, { text: "3:22" } ],
        [ { text: "6" }, { text: "Water" }, { text: "A Reign of Fish" }, { text: "2:32" } ],
        [ { text: "7" }, { text: "Moon" }, { text: "A Reign of Fish" }, { text: "2:12" } ],
        [ { text: "8" }, { text: "Storm" }, { text: "A Reign of Fish" }, { text: "13:00" } ],
    ];
    in property <[string]> track_keys;

    in property <[CardAdapter]> other-versions: [
        {
            image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "Epitaph Records • 2013-03-14"},
        },
        {
            image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "Valve Records • 2013-03-14"},
        },
        {
            image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "Deep Pressings • 2011-02-14"},
        },
        {
            image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
            title: {name: "A Reign of Fish"},
            sub-title: {name: "CD Folk • 2014-03-14"},
        },
    ];
    in property <string> dump;
    in property <bool> save;

    pure callback toggle_heart();

    pure callback sort_table(column: int, ascending: bool);
}

component RowMenu inherits PopupMenu {
    in property <string> key;

    PopupMenuButton {
        text: "Play Later";
        icon: @image-url("../../icons/phosphor/SVGs/regular/list-plus.svg");
        clicked => { AppState.play_later(key); }
    }
    PopupMenuButton {
        text: "Play Next";
        icon: @image-url("../../icons/phosphor/SVGs/regular/queue.svg");
        clicked => { AppState.play_next(key); }
    }
    PopupMenuButton {
        text: "Play Now";
        icon: @image-url("../../icons/phosphor/SVGs/regular/play.svg");
        clicked => { AppState.play_now(key); }
    }
    PopupMenuButton {
        text: "Details";
        icon: @image-url("../../icons/phosphor/SVGs/regular/info.svg");
        clicked => { Navigator.navigate("dimple://track/" + key); }
    }
}    

export component ReleaseDetails inherits ScrollView {
    horizontal-scrollbar-policy: always-off;

    in-out property <length> row-menu-x: 0;
    in-out property <length> row-menu-y: 0;
    in-out property <string> row-menu-key;

    VerticalBox {
        width: 100%;
        alignment: start;
        padding: 0;

        HorizontalBox {
            padding: 0;

            VerticalLayout {
                BorderImage {
                    width: Styles.thumbnail-width-extra-large;
                    height: Styles.thumbnail-width-extra-large;
                    key: ReleaseDetailsAdapter.key;
                    placeholder: @image-url("../../icons/phosphor/SVGs/regular/vinyl-record.svg");
                }
                HorizontalBox {
                    padding-left: 0;
                    padding-right: 0;
                    alignment: space-between;
                    Button {
                        icon: @image-url("../../icons/phosphor/SVGs/regular/play.svg");
                        colorize-icon: true;
                        clicked => { AppState.play_now(ReleaseDetailsAdapter.key); }
                    }
                    menu-area := ContextMenuArea {
                        Button {
                            icon: @image-url("../../icons/phosphor/SVGs/regular/dots-three.svg");
                            colorize-icon: true;
                            clicked => { menu-area.show({ x: self.width / 2, y: self.height / 2 }); }
                        }
                        Menu {
                            MenuItem {
                                title: "Play Later";
                                activated => { AppState.play_later(ReleaseDetailsAdapter.key); }
                            }
                            MenuItem {
                                title: "Play Next";
                                activated => { AppState.play_next(ReleaseDetailsAdapter.key); }
                            }
                            MenuItem {
                                title: "Play Now";
                                activated => { AppState.play_now(ReleaseDetailsAdapter.key); }
                            }
                        }
                    }
                    Button {
                        icon: ReleaseDetailsAdapter.save ? @image-url("../../icons/phosphor/SVGs/fill/heart-fill.svg")
                            : @image-url("../../icons/phosphor/SVGs/regular/heart.svg");
                        colorize-icon: true;                
                        clicked => { ReleaseDetailsAdapter.toggle_heart(); }
                    }
                }
            }
        
            VerticalBox {
                alignment: start;
                padding: 0;

                VerticalLayout {
                    PageTitle {
                        text: ReleaseDetailsAdapter.card.title.name;
                    }
                    if ReleaseDetailsAdapter.disambiguation != "": PageSubtitle {
                        text: ReleaseDetailsAdapter.disambiguation;
                    }
                }

                HorizontalLayout {
                    Label {
                        text: "By ";
                        font-size: Styles.default-font-size * 1.1;
                    }
                    Links {
                        links: ReleaseDetailsAdapter.artists;
                        height: self.preferred-height;
                        font-size: Styles.default-font-size * 1.1;
                    }
                }

                TagList {
                    tags: ReleaseDetailsAdapter.genres;
                    height: self.preferred-height;
                }
                if ReleaseDetailsAdapter.summary != "": Label {
                    text: ReleaseDetailsAdapter.summary;
                    wrap: word-wrap;
                    font-family: Styles.text-block-font-family;
                }
            }
        }

        // Tracks
        VerticalBox {
            alignment: start;
            padding: 0;
            row-menu := RowMenu {
                x: row-menu-x;
                y: row-menu-y;
                key: row-menu-key;
                width: self.preferred-width;
                height: self.preferred-height;
            }
            SectionTitle {
                text: "Tracks";
            }
            table := BasicTableView {
                columns: [
                    { title: "#", horizontal_stretch: 0.10 },
                    { title: "Title", horizontal_stretch: 0.50 },
                    { title: "Artist", horizontal_stretch: 0.30 },
                    { title: "Length", horizontal_stretch: 0.10 },
                    ];
                rows: ReleaseDetailsAdapter.track_items;
                sort-ascending(index) => { ReleaseDetailsAdapter.sort_table(index, true); }
                sort-descending(index) => { ReleaseDetailsAdapter.sort_table(index, false); }
                row-pointer-event(row, event, point) => {
                    if event.button == PointerEventButton.right 
                            && event.kind == PointerEventKind.down {
                        row-menu-x = point.x;
                        row-menu-y = point.y;
                        row-menu-key = ReleaseDetailsAdapter.track_keys[row];
                        row-menu.show();
                    }
                    else if event.button == PointerEventButton.left 
                            && row == table.current-row
                            && event.kind == PointerEventKind.down {
                        Navigator.navigate("dimple://track/" + ReleaseDetailsAdapter.track_keys[row]);
                    }
                }
            }
        }

        if ReleaseDetailsAdapter.other-versions.length > 0: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Other Versions";
            }
            CardGrid {
                cards: ReleaseDetailsAdapter.other-versions;
            }
        }     
        
        if ReleaseDetailsAdapter.links.length > 0: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Links";
            }
            for link in ReleaseDetailsAdapter.links: Link {
                url: link.url;
                name: link.name;
            }
        }     
        
        if SettingsAdapter.debug: VerticalBox {
            alignment: start;
            padding: 0;
            SectionTitle {
                text: "Debug";
            }
            Text {
                text: ReleaseDetailsAdapter.dump;
                wrap: word-wrap;
            }
        }        
    }
}
