import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { CardGrid } from "../components/card_grid.slint";
import { LinkAdapter, Links, Link} from "../components/link.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { CardGrid } from "../components/card_grid.slint";
import { LinkAdapter, Links, Link} from "../components/link.slint";
import { Styles, Navigator, AppState, Texxt, PageTitle, PageSubtitle, SectionTitle } from "../common.slint";
// import { ActionButtons, ActionButton } from "../components/action_buttons.slint";
import { PopupMenu, PopupMenuButton } from "../components/popup_menu.slint";
import { Tag, TagList, LinkButtons } from "../components/tag.slint";
import { BorderImage } from "../components/border_image.slint";

export global ReleaseDetailsAdapter {
    in property <string> key;
    in property <string> release-type: "Album";
    in property <CardAdapter> card: {
                image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
                title: {name: "A Reign of Fish"},
            };
    in property <string> disambiguation: "Not to be confused with Rain of Fish by Fargo.";
    in property <string> summary: "Fresh Pliers does it again with 'A Reign of Fish'. Ex nostrud culpa id veniam aliqua aliqua ipsum. Velit do id amet labore mollit id cillum commodo Lorem proident labore eu. Incididunt minim irure culpa excepteur officia sit consequat est mollit. Ipsum anim anim sunt dolore. Laborum consequat deserunt laboris ullamco cillum. Ullamco deserunt ut quis dolore aliquip esse consequat velit amet. Nulla tempor veniam dolor amet occaecat adipisicing nulla laboris.\n\nQui non irure anim irure nisi nulla ex aliquip. Sit do irure esse magna sit do eiusmod. Anim commodo velit non enim nulla.\n\nAnim incididunt dolore nulla laboris eu mollit Lorem minim reprehenderit in quis magna mollit. Labore Lorem esse anim ipsum esse irure ipsum proident deserunt officia consequat sunt sit. Ex laborum ipsum laboris nisi proident. Nulla culpa est commodo dolor. Magna sint id et ut esse mollit qui elit voluptate ea.";
    in property <[LinkAdapter]> genres: [{name: "heavy metal"},{name: "hard rock"},{name: "acid rock"},{name: "heavy metal"},{name: "hard rock"},{name: "acid rock"},{name: "heavy metal"},{name: "hard rock"},{name: "acid rock"},];
    in property <[LinkAdapter]> links: [{name: "https://bandcamp.com/arof",url: "internal://release/1234"}];
    in property <[LinkAdapter]> artists: [{name: "Fresh Pliers"},{name: "Example Band"},{name: "Teal Cup"},];
    in property <[[StandardListViewItem]]> row_data: [
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
        [ { text: "hi" }, { text: "hi" }, { text: "hi" }, { text: "hi" } ],
    ];
    in property <[string]> row_keys;

    in property <string> dump;
    in property <bool> save;
    in property <bool> love;
    in property <bool> download;

    pure callback set_save(bool);
    pure callback set_download(bool);
    pure callback set_love(bool);

    pure callback play_now(string /* key */);
    pure callback play_next(string /* key */);
    pure callback play_later(string /* key */);

    pure callback play_track_now(string /* key */);
    pure callback play_track_next(string /* key */);
    pure callback play_track_later(string /* key */);

    pure callback sort_table(int /* column */, bool /* ascending */);
}

// popup := PopupMenu {
//     x: popup-x; 
//     y: popup-y; 

//     PopupMenuButton {
//         text: "Play Later";
//         icon: @image-url("../../icons/phosphor/SVGs/regular/list-plus.svg");
//         clicked => { ReleaseDetailsAdapter.play_track_later(ReleaseDetailsAdapter.row_keys[popup-row]); }
//     }
//     PopupMenuButton {
//         text: "Play Next";
//         icon: @image-url("../../icons/phosphor/SVGs/regular/queue.svg");
//         clicked => { ReleaseDetailsAdapter.play_track_next(ReleaseDetailsAdapter.row_keys[popup-row]); }
//     }
//     PopupMenuButton {
//         text: "Play Now";
//         icon: @image-url("../../icons/phosphor/SVGs/regular/play.svg");
//         clicked => { ReleaseDetailsAdapter.play_track_now(ReleaseDetailsAdapter.row_keys[popup-row]); }
//     }
//     PopupMenuButton {
//         text: "Track Info";
//         icon: @image-url("../../icons/phosphor/SVGs/regular/info.svg");
//         clicked => { Navigator.navigate("dimple://track/" + ReleaseDetailsAdapter.row_keys[root.popup-row]); }
//     }
// }    

export component ReleaseDetails inherits ScrollView {
    horizontal-scrollbar-policy: always-off;
    viewport-height: v.preferred-height;

    in-out property <length> popup-x;
    in-out property <length> popup-y;
    in-out property <int> popup-row;

    v := VerticalBox {
        alignment: start;
        padding: 0;

        HorizontalBox {
            alignment: start;
            padding: 0;

            BorderImage {
                width: Styles.thumbnail-width-extra-large;
                height: Styles.thumbnail-width-extra-large;
                source: ReleaseDetailsAdapter.card.image.image;
            }
            VerticalBox {
                alignment: start;
                padding: 0;

                VerticalLayout {
                    PageTitle {
                        text: ReleaseDetailsAdapter.card.title.name;
                        wrap: word-wrap;
                    }
                    if ReleaseDetailsAdapter.disambiguation != "": PageSubtitle {
                        text: ReleaseDetailsAdapter.disambiguation;
                    }
                }
                LinkButtons {
                    links: ReleaseDetailsAdapter.links;
                    height: self.preferred-height;
                }
                // if ReleaseDetailsAdapter.artists.length > 0: HorizontalLayout {
                //     alignment: start;
                //     if ReleaseDetailsAdapter.release-type != "": Texxt {
                //         text: "\{ReleaseDetailsAdapter.release-type} by ";
                //     }
                //     // TODO this blows up
                //     Links {
                //         links: ReleaseDetailsAdapter.artists;
                //         height: self.preferred-height;
                //     }
                // }
                Links {
                    links: ReleaseDetailsAdapter.artists;
                    height: self.preferred-height;
                }
                TagList {
                    tags: ReleaseDetailsAdapter.genres;
                    height: self.preferred-height;
                }
                if ReleaseDetailsAdapter.summary != "": Texxt {
                    text: ReleaseDetailsAdapter.summary;
                    wrap: word-wrap;
                }
            }
        }

        // Tracks
        table := StandardTableView {
            columns: [
                { title: "#", horizontal_stretch: 0.10 },
                { title: "Title", horizontal_stretch: 0.50 },
                { title: "Artist", horizontal_stretch: 0.30 },
                { title: "Length", horizontal_stretch: 0.10 },
                ];
            rows: ReleaseDetailsAdapter.row_data;
            sort-ascending(index) => { ReleaseDetailsAdapter.sort_table(index, true); }
            sort-descending(index) => { ReleaseDetailsAdapter.sort_table(index, false); }
            // row-pointer-event(row, event, point) => {
            //     if event.button == PointerEventButton.right 
            //             && event.kind == PointerEventKind.down {
            //         popup-x = table.absolute-position.x + point.x;
            //         popup-y = table.absolute-position.y + point.y;
            //         popup-row = row;
            //         popup.show();
            //     }
            //     else if event.button == PointerEventButton.left 
            //             && row == table.current-row
            //             && event.kind == PointerEventKind.down {
            //         Navigator.navigate("dimple://track/" + ReleaseDetailsAdapter.row_keys[row]);
            //     }
            // }
        }

        // if ReleaseDetailsAdapter.links.length > 0: VerticalBox {
        //     alignment: start;
        //     padding: 0;
        //     SectionTitle {
        //         text: "Links";
        //     }
        //     for link in ReleaseDetailsAdapter.links: Link {
        //         url: link.url;
        //         name: link.name;
        //     }
        // }
    }
}
