import { ScrollView, VerticalBox, GridBox, HorizontalBox } from "std-widgets.slint";
import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import { CardAdapter, Card } from "../components/card.slint";
import {Styles, Texxt, PageTitle, PageSubtitle} from "../common.slint";
import { PopupMenu, PopupMenuButton } from "../components/popup_menu.slint";

export global ReleaseListAdapter {
    in-out property <[CardAdapter]> cards: [{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },{
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png")},
        title: {name: "A Reign of Fish"},
        sub-title: {name: "Anchor System"},
    },];
}

component CardMenu inherits PopupMenu {
    PopupMenuButton {
        text: "Play Later";
        icon: @image-url("../../icons/phosphor/SVGs/regular/list-plus.svg");
        // clicked => { ReleaseDetailsAdapter.play_track_later(ReleaseDetailsAdapter.row_keys[popup-row]); }
    }
    PopupMenuButton {
        text: "Play Next";
        icon: @image-url("../../icons/phosphor/SVGs/regular/queue.svg");
        // clicked => { ReleaseDetailsAdapter.play_track_next(ReleaseDetailsAdapter.row_keys[popup-row]); }
    }
    PopupMenuButton {
        text: "Play Now";
        icon: @image-url("../../icons/phosphor/SVGs/regular/play.svg");
        // clicked => { ReleaseDetailsAdapter.play_track_now(ReleaseDetailsAdapter.row_keys[popup-row]); }
    }
    PopupMenuButton {
        text: "Details";
        icon: @image-url("../../icons/phosphor/SVGs/regular/info.svg");
        // clicked => { Navigator.navigate("dimple://track/" + ReleaseDetailsAdapter.row_keys[root.popup-row]); }
    }
}    

export component ReleaseList inherits ScrollView {
    horizontal-scrollbar-policy: always-off;

    in-out property <length> card-menu-x;
    in-out property <length> card-menu-y;
    card-menu := CardMenu {
        x: card-menu-x;
        y: card-menu-y;
        width: self.preferred-width;
        height: self.preferred-height;
    }

    VerticalBox {
        width: 100%;
        alignment: start;
        padding: 0;

        VerticalLayout {
            PageTitle {
                text: "Releases";
            }
            PageSubtitle {
                text: ReleaseListAdapter.cards.length + " items";
            }
        }
    
        CardGrid {
            cards: ReleaseListAdapter.cards;
            pointer-event(event, x, y) => {
                if event.kind == PointerEventKind.up && event.button == PointerEventButton.right {
                    root.card-menu-x = x;
                    root.card-menu-y = y;
                    card-menu.show();
                }
            }
        }
    }
}

