import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView, ComboBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { CardGrid } from "../components/card_grid.slint";
import { LinkAdapter, Links, Link} from "../components/link.slint";
import { Palette, Navigator, AppState } from "../common.slint";
import {MediumAdapter} from "../components/medium.slint";
import { TrackList } from "../components/track_list.slint";

export struct ReleaseGroupDetailsAdapter {
    key: string,
    card: CardAdapter,
    disambiguation: string,
    summary: string,
    genres: [LinkAdapter],
    releases: [CardAdapter],
    links: [LinkAdapter],
    primary_type: string,
    artists: [LinkAdapter],

    // From the default and/or selected release.
    media: [MediumAdapter],
    dump: string,

    release_options: [string],
    selected_release_option: string,
}

export component ReleaseGroupDetails inherits ScrollView {
    VerticalBox {
        alignment: start;
        spacing: StyleMetrics.layout-spacing * 2;
        // Header: Image, Title, Artists, Genres, Summary
        HorizontalLayout {
            alignment: start;
            spacing: StyleMetrics.layout-spacing;
            // Image
            Rectangle {
                width: Palette.thumbnail-width-extra-large;
                height: Palette.thumbnail-width-extra-large;
                border-radius: Palette.thumbnail-border-radius;
                border-color: Palette.thumbnail-border-color;
                border-width: Palette.thumbnail-border-width;
                clip: true;
                Image {
                    width: Palette.thumbnail-width-extra-large;
                    height: Palette.thumbnail-width-extra-large;
                    source: model.card.image.image;
                }
            }
            VerticalLayout {
                alignment: start;
                spacing: StyleMetrics.layout-spacing;
                // Text {
                //     text: "Artist";
                //     font-size: 1.3rem;
                // }
                // Title
                VerticalLayout {
                    Text {
                        text: model.card.title.name;
                        font-weight: Palette.font-weight-bold;
                        font-size: 4rem;
                        wrap: word-wrap;
                    }
                    // Disambiguation
                    if model.disambiguation > 0: HorizontalLayout {
                        spacing: 4px;
                        Image {
                            source: @image-url("../../icons/phosphor/SVGs/regular/info.svg");
                            width: 1.5rem;
                            colorize: StyleMetrics.default-text-color;
                            padding-right: 8px;
                        }
                        Text {
                            vertical-alignment: bottom;
                            text: model.disambiguation;
                            // font-weight: Palette.font-weight-bold;
                            font-size: 1.3rem;
                            color: StyleMetrics.default-text-color.darker(0.5);
                        }
                    }
                }
                // TODO Change this to date, type, and then artists.
                // Type and artists
                if model.artists.length > 0: HorizontalLayout {
                    alignment: start;
                    Text {
                        text: "\{model.primary-type} by ";
                        font-size: 1.3rem;
                    }
                    Links {
                        links: model.artists;
                        font-size: 1.3rem;
                    }
                }
                // Genres
                if model.genres.length > 0: HorizontalLayout {
                    alignment: start;
                    Text {
                        text: "In ";
                        font-size: 1.3rem;
                    }    
                    Links {
                        links: model.genres;
                        font-size: 1.3rem;
                    }
                }
                // Summary
                Text {
                    text: model.summary;
                    wrap: word-wrap;
                    font-size: 1.2rem;
                }
            }
        }

        // Releases Combo
        if model.release-options.length > 0: VerticalLayout {
            spacing: StyleMetrics.layout-spacing * 0.50;
            // Text {
            //     text: "Release Versions";
            //     font-weight: Palette.font-weight-bold;
            //     font-size: 2rem;
            // }
            ComboBox {
                width: self.preferred-width;
                height: self.preferred-height;
                model: model.release-options;
                current-value: model.selected-release-option;
                selected => { AppState.release_group_details_release_selected(self.current-value); }
            }
        }
        
        // Media and Tracks
        if model.media.length > 0: VerticalLayout {
            spacing: 16px;
            for medium in model.media: VerticalLayout {
                Text {
                    text: medium.title;
                    font-weight: Palette.font-weight-bold;
                    font-size: 2rem;
                }
                // https://github.com/slint-ui/slint/blob/master/internal/compiler/widgets/cupertino-base/tableview.slint
                TrackList {
                    tracks: medium.tracks;
                }
            }
        }

        // // Releases Grid
        // if model.releases.length > 0: VerticalLayout {
        //     spacing: StyleMetrics.layout-spacing * 0.50;
        //     Text {
        //         text: "All Versions";
        //         font-weight: Palette.font-weight-bold;
        //         font-size: 2rem;
        //     }
        //     CardGrid {
        //         cards: model.releases;
        //         parent-width: root.width;
        //     }
        // }

        // Links
        if model.links.length > 0: VerticalLayout {
            Text {
                text: "Links";
                font-weight: Palette.font-weight-bold;
                font-size: 2rem;
            }
            for link in model.links: Link {
                url: link.url;
                name: link.name;
            }
        }

        // Debug Dump
        if AppState.debug: VerticalLayout {
            Text {
                text: "Debug";
                font-weight: Palette.font-weight-bold;
                font-size: 2rem;
            }
            Text {
                text: model.dump;
                wrap: word-wrap;
            }
        }
    }

    in property <ReleaseGroupDetailsAdapter> model: {
        // id: "123-123-123-123",
        // title: "A Reign of Fish",
        card: {
            image: {image: @image-url("../../images/dark.png"),name: "A Reign of Fish",url: "internal://release/1234"},
            title: {name: "A Reign of Fish",url: "internal://release/1234"},
            sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
        },
        disambiguation: "regular kind",
        summary: "Cupidatat do excepteur sit quis officia nulla. Excepteur eu ad reprehenderit eiusmod minim esse ullamco eiusmod quis esse eiusmod. Pariatur minim aliquip voluptate aliquip irure Lorem incididunt adipisicing sit ullamco consectetur. Esse mollit eu sint aliqua dolor consectetur exercitation officia. Sit ad voluptate enim dolor irure. Dolore incididunt ipsum officia aliqua sit consectetur ex et sunt consequat minim.Amet tempor officia nulla est commodo officia exercitation et sint eiusmod proident velit adipisicing. Qui commodo consectetur ea in voluptate. Id laborum aute fugiat consequat fugiat dolor ullamco aliquip nostrud elit anim magna et.",
        genres: [ {name: "fish jazz",url: "internal://release/1234"} ],
        artists: [ 
            { name: "Shield Fish", url: "internal://release/1234" }, 
            { name: "Zim Babwe", url: "internal://release/1234" }, 
            { name: "Vic Toria", url: "internal://release/1234" }, 
        ],
        links: [ 
            { name: "Shield Fish", url: "internal://release/1234" }, 
            { name: "Zim Babwe", url: "internal://release/1234" }, 
            { name: "Vic Toria", url: "internal://release/1234" }, 
        ],
        releases: [
            { 
                image: {image: @image-url("../../images/dark.png"),name: "A Reign of Fish",url: "internal://release/1234"},
                title: {name: "A Reign of Fish",url: "internal://release/1234"},
                sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
            },
            { 
                image: {image: @image-url("../../images/dark.png"),name: "A Reign of Fish",url: "internal://release/1234"},
                title: {name: "A Reign of Fish",url: "internal://release/1234"},
                sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
            },
            { 
                image: {image: @image-url("../../images/dark.png"),name: "A Reign of Fish",url: "internal://release/1234"},
                title: {name: "A Reign of Fish",url: "internal://release/1234"},
                sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
            },
        ],
        primary-type: "Album",
        media: [
            {
                title: "Disc 1 of 2",
                tracks: [
                    { title: { name: "Graphing Pencil" }, track_number: 1, length: "5:03", 
                        artists: [{ name: "Toops" }, { name: "Flanger and the Twins"}, { name: "The Leech"} ], 
                        plays: 17, },
                    { title: { name: "Funky Zow" }, track_number: 2, length: "2:31", 
                        artists: [{ name: "Toops" }, { name: "Flanger and the Twins"}, { name: "The Leech"} ], 
                        plays: 21, },
                    { title: { name: "Turn Up For What? When? I'm busy that night." }, track_number: 3, length: "1:21", 
                        artists: [{ name: "Toops" }, { name: "Flanger and the Twins"}, { name: "The Leech"} ], 
                        plays: 79, },
                ]
            },
            {
                title: "Disc 2 of 2",
                tracks: [
                    { title: { name: "Graphing Pencil" }, track_number: 1, length: "5:03", 
                        artists: [{ name: "Toops" }, { name: "Flanger and the Twins"}, { name: "The Leech"} ], 
                        plays: 17, },
                    { title: { name: "Funky Zow" }, track_number: 2, length: "2:31", 
                        artists: [{ name: "Toops" }, { name: "Flanger and the Twins"}, { name: "The Leech"} ], 
                        plays: 21, },
                    { title: { name: "Turn Up For What? When? I'm busy that night." }, track_number: 3, length: "1:21", 
                        artists: [{ name: "Toops" }, { name: "Flanger and the Twins"}, { name: "The Leech"} ], 
                        plays: 79, },
                ]
            },
        ]
    };
}
