/**
    - language: Will be used to narrow wikidata queries, select bios, and for i18n.
    - libraries: List of the enabled libraries. I guess this should really be a
      plugin system but we'll get there later. For now it's ReferenceMachine.
      These will likely include auth flows.
    - import/export: still not sure about mp3 import or mp3 library, but still
      things like csv or json. I want to import my history and I don't see
      a reason for those to be libraries. 
    - cache stats, clear, relocate, etc.
 */


import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { StyleMetrics , ScrollView, ListView, GroupBox, Button, CheckBox, Slider} from "std-widgets.slint";
import { AppState, Palette, Navigator } from "../common.slint";

export global SettingsAdapter {
    in property <[string]> cache_stats;
    in property <[string]> database_stats;
    pure callback set_online(bool);
    pure callback set_debug(bool);
    pure callback set_font_size(float);
}

component General inherits VerticalBox {
    Text {
        text: "General";
        font-size: 2rem;
    }

    HorizontalBox {
        alignment: LayoutAlignment.start;
        Text {
            text: "Font Size";
            vertical-alignment: center;
        }

        Slider {
            width: 200px;
            minimum: 1;
            maximum: 24;
            changed => {
                SettingsAdapter.set_font_size(self.value);
            }
        }
    }

    HorizontalBox {
        Text {
            text: "Online?";
            vertical-alignment: center;
        }

        CheckBox {
            checked: AppState.online;
            toggled => {
                SettingsAdapter.set_online(self.checked);
            }
        }
    }
}

component Database inherits VerticalBox {
    Text {
        text: "Database";
        font-size: 2rem;
    }

    VerticalBox {
        for stat in SettingsAdapter.database-stats: Text {
            text: stat;
            vertical-alignment: center;
        }
    }
}

component Cache inherits VerticalBox {
    Text {
        text: "Cache";
        font-size: 2rem;
    }

    for stat in SettingsAdapter.cache-stats: Text {
        text: stat;
        vertical-alignment: center;
    }
}

component Development inherits VerticalBox {
    Text {
        text: "Development";
        font-size: 2rem;
    }

    HorizontalBox {
        Text {
            text: "Show model JSON?";
            vertical-alignment: center;
        }

        CheckBox {
            checked: AppState.debug;
            toggled => {
                SettingsAdapter.set_debug(self.checked);
            }
        }
    }
}

export component Settings inherits VerticalBox {
    in property <length> header-font-size: 1.5rem;

    Text {
        text: "Settings";
        font-size: 3rem;
    }

    ScrollView {
        VerticalBox {
            General { }

            Database { }

            Cache { }

            Development { }
        }
    }
}
