import { CardGrid, CardGridAdapter } from "../components/card_grid.slint";
import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { CardAdapter } from "../components/card.slint";
import { StyleMetrics , ScrollView, ListView, StandardTableView} from "std-widgets.slint";
import { AppState } from "../common.slint";

export global TrackListAdapter {
    in property <[[StandardListViewItem]]> row_data;
    pure callback sort_model([[StandardListViewItem]], int, bool) -> [[StandardListViewItem]];
    pure callback current_row_changed(int);
}
 
export component TrackList inherits VerticalLayout {
    // https://github.com/slint-ui/slint/blob/master/examples/gallery/ui/pages/table_view_page.slint
    property <int> sort-index: -1;
    property <bool> sort-acending;
        
    StandardTableView {
        height: 100%;
        width: 100%;
        columns: [
            { title: "Title" },
            { title: "Album" },
            { title: "Artist" },
            { title: "Track #" },
            { title: "Plays" },
            { title: "Length" },
        ];
        rows: TrackListAdapter.sort_model(TrackListAdapter.row_data, root.sort-index, root.sort-acending);
        current-row-changed(row) => { 
            TrackListAdapter.current_row_changed(row);
        }
        sort-ascending(index) => {
            root.sort-index = index;
            root.sort-acending = true;
        }
        sort-descending(index) => {
            root.sort-index = index;
            root.sort-acending = false;
        }        
    }
    Text {
        horizontal-alignment: right;
        text: TrackListAdapter.row_data.length + " items";
    }
}
