import { Styles } from "../common.slint";
import { Palette } from "std-widgets.slint";
import { LazyImage } from "lazy_image.slint";

export component BorderImage inherits TouchArea {
    in property <string> key;
    in property <image> placeholder;
    mouse-cursor: MouseCursor.pointer;
    Rectangle {
        width: root.width;
        height: root.height;
        border-radius: Styles.thumbnail-border-radius;
        border-color: Palette.border;
        border-width: Styles.thumbnail-border-width;
        clip: true;
        background: white;
        LazyImage {
            width: root.width;
            height: root.height;
            key: root.key;
            placeholder: root.placeholder;
        }
    }
}
