import { Button, VerticalBox , ScrollView} from "std-widgets.slint";
import { Card, CardAdapter } from "card.slint";
import { Styles, Navigator, Texxt } from "../common.slint";
import {StyleMetrics, HorizontalBox} from "std-widgets.slint";

export struct CardGridAdapter {
    cards: [CardAdapter],
}

export component CardGrid inherits VerticalBox {
    in-out property <[CardAdapter]> cards: cards_ph;
    in property <int> max-rows: 0;
    in property <length> card-width: Styles.thumbnail-width-large;

    property <int> cols: Math.max(1, Math.floor(self.width / (self.card-width + self.spacing)));
    property <int> rows: self.max-rows >= 1 ? self.max-rows : Math.ceil(cards.length / cols);
    // property <length> addl-spacing: (self.width - ((self.card-width + self.spacing) * cols)) / cols;

    alignment: start;
    padding: 0;

    callback pointer-event(event: PointerEvent, x: length, y: length, model: CardAdapter);

    for row in rows: HorizontalBox {
        alignment: start;
        padding: 0;
        for col in Math.min(cols, cards.length - (row * cols)): Card {
            // width: root.card-width + addl-spacing;
            model: cards[row * cols + col];
            pointer-event(event, x, y, model) => { root.pointer-event(event, x, y, model); }
        }
    }

    property <CardAdapter> card_ph: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
    };

    property <CardAdapter> card_ph2: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/users-three.png"),name: "Bob The Wonderful Explorer",url: "internal://release/1234"},
        title: {name: "Bob The Wonderful Explorer",url: "internal://release/1234"},
        sub-title: {name: "A man of infinite stories and very few talents.",url: "internal://artist/9876"},
    };

    property <[CardAdapter]> cards_ph: [card_ph, card_ph2, card_ph, card_ph2, card_ph2, card_ph, card_ph, card_ph2, card_ph2, card_ph2, card_ph, card_ph, card_ph, card_ph2, card_ph];
}

