import { Button, VerticalBox , ScrollView} from "std-widgets.slint";
import { Styles, Navigator, AppState } from "../common.slint";
import {StyleMetrics, Palette, StandardButton} from "std-widgets.slint";
import {ImageLinkAdapter, LinkAdapter} from "../components/link.slint";
import { Link } from "link.slint";
import { BorderImage } from "border_image.slint";
import { LazyImage } from "lazy_image.slint";

export struct CardAdapter {
    image: ImageLinkAdapter,
    title: LinkAdapter,
    sub-title: LinkAdapter,
    key: string,
}

// TODO temp copied from BorderImage, as to not blow up the whole app
// but this just gets merged with it. I think every image becomes a lazy
// image.
export component LazyBorderImage inherits TouchArea {
    in property <string> key;
    in property <image> placeholder;
    mouse-cursor: MouseCursor.pointer;
    Rectangle {
        width: root.width;
        height: root.height;
        border-radius: Styles.thumbnail-border-radius;
        border-color: Palette.border;
        border-width: Styles.thumbnail-border-width;
        clip: true;
        background: white;
        LazyImage {
            width: root.width;
            height: root.height;
            key: root.key;
            placeholder: root.placeholder;
        }
    }
}

export component VirtualCard inherits VerticalBox {
    in property <CardAdapter> model: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
    };

    width: Styles.thumbnail-width-large;
    alignment: start;
    padding: 0;
    spacing: 4px;

    LazyBorderImage {
        width: root.width;
        height: root.width;
        placeholder: @image-url("../../icons/phosphor/PNGs/regular/users-three.png");
        key: model.key;
        clicked => { Navigator.navigate(model.image.url); }
        ContextMenuArea {
            Menu {
                MenuItem {
                    title: "Play Later";
                    activated => { AppState.play_later(model.key); }
                }
                MenuItem {
                    title: "Play Next";
                    activated => { AppState.play_next(model.key); }
                }
                MenuItem {
                    title: "Play Now";
                    activated => { AppState.play_now(model.key); }
                }
                MenuItem {
                    title: "Details";
                    activated => { Navigator.navigate(model.title.url); }
                }
            }
        }
    }

    Link {
        url: model.title.url;
        name: model.title.name;
    }
    Link {
        url: model.sub-title.url;
        name: model.sub-title.name;
    }
}

export component Card inherits VerticalBox {
    in property <CardAdapter> model: {
        image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Fish",url: "internal://release/1234"},
        title: {name: "A Reign of Fish",url: "internal://release/1234"},
        sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
    };

    callback pointer-event(event: PointerEvent, x: length, y: length, model: CardAdapter);

    width: Styles.thumbnail-width-large;
    alignment: start;
    padding: 0;
    spacing: 4px;

    BorderImage {
        source: model.image.image;
        width: root.width;
        height: root.width;
        clicked => { Navigator.navigate(model.image.url); }
        pointer-event(event) => { root.pointer-event(event, self.mouse-x, self.mouse-y, model); }
    }
    Link {
        url: model.title.url;
        name: model.title.name;
    }
    Link {
        url: model.sub-title.url;
        name: model.sub-title.name;
    }
}

// export component PlayableCard inherits VerticalBox {
//     in property <CardAdapter> model: {
//         image: {image: @image-url("../../icons/phosphor/PNGs/regular/vinyl-record.png"),name: "A Reign of Fish",url: "internal://release/1234"},
//         title: {name: "A Reign of Fish",url: "internal://release/1234"},
//         sub-title: {name: "Fresh Pliers",url: "internal://artist/9876"},
//     };

//     callback pointer-event(event: PointerEvent, x: length, y: length, model: CardAdapter);

//     width: Styles.thumbnail-width-large;
//     alignment: start;
//     padding: 0;
//     spacing: 4px;

//     ta := TouchArea {
//         Rectangle {
//             img := BorderImage {
//                 source: model.image.image;
//                 width: root.width;
//                 height: root.width;
//                 clicked => { Navigator.navigate(model.image.url); }
//                 pointer-event(event) => { root.pointer-event(event, self.mouse-x, self.mouse-y, model); }
//             }
//             Button {
//                 x: 4px;
//                 y: img.y + img.height - self.height - 4px;
//                 opacity: ta.has-hover ? 1 : 0;
//                 animate opacity {
//                      duration: 100ms;
//                 }
//                 icon: @image-url("../../icons/phosphor/SVGs/regular/play.svg");
//                 colorize-icon: true;                
//             }
//             Button {
//                 x: img.width - self.width - 4px;
//                 y: img.y + img.height - self.height - 4px;
//                 opacity: ta.has-hover ? 1 : 0;
//                 animate opacity {
//                      duration: 100ms;
//                 }
//                 icon: @image-url("../../icons/phosphor/SVGs/regular/dots-three.svg");
//                 colorize-icon: true;                
//             }
//         }
//     }
//     Link {
//         url: model.title.url;
//         name: model.title.name;
//     }
//     Link {
//         url: model.sub-title.url;
//         name: model.sub-title.name;
//     }
// }
