import { FlowLayoutResults } from "./flow_layout.slint";
import { FlowLayoutLogic, FlowLayout, FlowLayoutItem } from "flow_layout.slint";
import { LinkAdapter, Links, Link} from "../components/link.slint";
import { Navigator, Texxt, Styles } from "../common.slint";
import { Palette, VerticalBox, Button } from "std-widgets.slint";
import { BorderImage } from "border_image.slint";

export component Tag inherits TouchArea {
    in-out property <string> text: "heavy metal";
    in-out property <color> color: #638d5d;

    preferred-width: r.preferred-width;
    preferred-height: r.preferred-height;

    r := Rectangle {
        clip: true;
        border-width: Styles.thumbnail-border-width;
        border-color: Palette.border;
        border-radius: Styles.thumbnail-border-radius;

        background: root.has-hover 
            ? Palette.accent-background
            : color;

        HorizontalLayout {
            padding: 4px;
            text := Texxt {
                text: root.text;
                wrap: no-wrap;
                overflow: clip;
                color: root.has-hover 
                    ? Palette.accent-foreground
                    : Palette.control-foreground;
                
            }
        }
    }
}

component LinkButton inherits TouchArea {
    in property <image> source: @image-url("../../icons/phosphor/SVGs/regular/spotify-logo.svg");

    preferred-width: r.preferred-width;
    preferred-height: r.preferred-height;
    
    r := Rectangle {
        preferred-width: image.width + 4px;
        preferred-height: image.height + 4px;
        // background: Palette.control-background;
        background: root.has-hover ? Palette.accent-background :Palette.control-background;
        border-radius: self.width;
        border-width: 1px;
        border-color: Palette.border;

        image := Image {
            source: root.source;
            preferred-width: 24px;
            preferred-height: 24px;
            colorize: root.has-hover ? Palette.accent-foreground : Palette.control-foreground;
        }
    }
}

export component TagList inherits FlowLayout {
    in-out property <[LinkAdapter]> tags: [{name: "heavy metal"},{name: "heavy metal thing cup stuff"},{name: "hard rock"},{name: "acid rock"}];
    in-out property <[color]> colors: [#638d5d, #838d5d, #5d8a8d, #7f5d8d, #8d6b5d, #5d648d, #8d825d];
    
    for i in tags.length: FlowLayoutItem {
        item-infos: parent.item-infos;
        index: i;
        Tag {
            color: colors[Math.mod(i, colors.length)];
            text: tags[i].name;
            clicked => { Navigator.navigate(tags[i].url); }
        }
    }
}

export component LinkButtons inherits FlowLayout {
    in-out property <[LinkAdapter]> links: [{name: "heavy metal"},{name: "heavy metal thing cup stuff"},{name: "hard rock"},{name: "acid rock"}];
    
    for i in links.length: FlowLayoutItem {
        item-infos: parent.item-infos;
        index: i;
        LinkButton {
            source: @image-url("../../icons/phosphor/SVGs/regular/spotify-logo.svg");
            clicked => { Navigator.navigate(links[i].url); }
        }
    }
}
