name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  default:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        # os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo test --release -- --skip player 
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with: 
          name: ${{ matrix.os }}
          path: |
            target/release/dimple_ui_slint
            target/release/dimple_ui_slint.exe
