name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo build
      - run: cargo test
      - uses: actions/upload-artifact@v2
        with: 
          name: ${{ matrix.os }}
          path: |
            target/debug/dimple_ui_slint
            target/debug/dimple_ui_slint.exe
